# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  App\Service\PlaylistAnalysis\Contract\PlaylistDataProviderInterface:
    class: App\Service\PlaylistAnalysis\DoctrinePlaylistDataProvider
    arguments:
      $playlistRepository: '@App\Repository\PlaylistRepository'
      $playlistTypeRepository: '@App\Repository\PlaylistTypeRepository'
  App\Service\PlaylistAnalysis\Contract\SongFrequencyCalculatorInterface:
    class: App\Service\PlaylistAnalysis\SongFrequencyCalculator

  App\Service\PlaylistAnalysis\Contract\PlaylistSimilarityCalculatorInterface:
    class: App\Service\PlaylistAnalysis\JaccardSimilarityCalculator

  App\Service\PlaylistAnalysis\Contract\ArtistAnalyzerInterface:
    class: App\Service\PlaylistAnalysis\ArtistFrequencyAnalyzer

  App\Service\PlaylistAnalysis\Contract\PlaylistSongExtractorInterface:
    class: App\Service\PlaylistAnalysis\PlaylistSongExtractor

  App\Service\PlaylistAnalysis\Contract\CommonSongAnalyzerInterface:
    class: App\Service\PlaylistAnalysis\CommonSongAnalyzer
    arguments:
      $dataProvider: '@App\Service\PlaylistAnalysis\Contract\PlaylistDataProviderInterface'
      $frequencyCalculator: '@App\Service\PlaylistAnalysis\Contract\SongFrequencyCalculatorInterface'

  App\Service\PlaylistAnalysis\Contract\PlaylistTypeComparatorInterface:
    class: App\Service\PlaylistAnalysis\PlaylistTypeComparator
    arguments:
      $dataProvider: '@App\Service\PlaylistAnalysis\Contract\PlaylistDataProviderInterface'
      $songExtractor: '@App\Service\PlaylistAnalysis\Contract\PlaylistSongExtractorInterface'
      $similarityCalculator: '@App\Service\PlaylistAnalysis\Contract\PlaylistSimilarityCalculatorInterface'

  App\Service\PlaylistAnalysis\Contract\UniquePlaylistSongAnalyzerInterface:
    class: App\Service\PlaylistAnalysis\UniquePlaylistSongAnalyzer
    arguments:
      $dataProvider: '@App\Service\PlaylistAnalysis\Contract\PlaylistDataProviderInterface'
      $songExtractor: '@App\Service\PlaylistAnalysis\Contract\PlaylistSongExtractorInterface'

  App\Service\PlaylistAnalysis\Contract\SeasonalPatternAnalyzerInterface:
    class: App\Service\PlaylistAnalysis\SeasonalPatternAnalyzer
    arguments:
      $dataProvider: '@App\Service\PlaylistAnalysis\Contract\PlaylistDataProviderInterface'
      $commonSongAnalyzer: '@App\Service\PlaylistAnalysis\Contract\CommonSongAnalyzerInterface'
      $songExtractor: '@App\Service\PlaylistAnalysis\Contract\PlaylistSongExtractorInterface'
      $artistAnalyzer: '@App\Service\PlaylistAnalysis\Contract\ArtistAnalyzerInterface'

  App\Service\PlaylistAnalysis\Contract\AnalysisSummaryGeneratorInterface:
    class: App\Service\PlaylistAnalysis\AnalysisSummaryGenerator

  App\Service\PlaylistAnalysis\PlaylistAnalysisService:
    arguments:
      $dataProvider: '@App\Service\PlaylistAnalysis\Contract\PlaylistDataProviderInterface'
      $commonSongAnalyzer: '@App\Service\PlaylistAnalysis\Contract\CommonSongAnalyzerInterface'
      $typeComparator: '@App\Service\PlaylistAnalysis\Contract\PlaylistTypeComparatorInterface'
      $uniqueSongAnalyzer: '@App\Service\PlaylistAnalysis\Contract\UniquePlaylistSongAnalyzerInterface'
      $patternAnalyzer: '@App\Service\PlaylistAnalysis\Contract\SeasonalPatternAnalyzerInterface'
      $similarityCalculator: '@App\Service\PlaylistAnalysis\Contract\PlaylistSimilarityCalculatorInterface'
      $summaryGenerator: '@App\Service\PlaylistAnalysis\Contract\AnalysisSummaryGeneratorInterface'

  # Direct class aliases for when you need to inject specific implementations
  App\Service\PlaylistAnalysis\DoctrinePlaylistDataProvider: ~
  App\Service\PlaylistAnalysis\SongFrequencyCalculator: ~
  App\Service\PlaylistAnalysis\JaccardSimilarityCalculator: ~
  App\Service\PlaylistAnalysis\ArtistFrequencyAnalyzer: ~
  App\Service\PlaylistAnalysis\PlaylistSongExtractor: ~
  App\Service\PlaylistAnalysis\CommonSongAnalyzer: ~
  App\Service\PlaylistAnalysis\PlaylistTypeComparator: ~
  App\Service\PlaylistAnalysis\UniquePlaylistSongAnalyzer: ~
  App\Service\PlaylistAnalysis\SeasonalPatternAnalyzer: ~
  App\Service\PlaylistAnalysis\AnalysisSummaryGenerator: ~

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Configure DataFixtures for dependency injection
  App\DataFixtures\:
    resource: '../src/DataFixtures/'
    tags: [ 'doctrine.fixture.orm' ]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones