# config/services.yaml

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc

  # ========================================================================
  # INTERFACE BINDING - Match the Contract namespace
  # ========================================================================

  App\Service\PlaylistAnalysis\Contract\PlaylistDataProviderInterface:
    class: App\Service\PlaylistAnalysis\DoctrinePlaylistDataProvider

  # ========================================================================
  # AUTO-DISCOVERY
  # ========================================================================

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Configure DataFixtures for dependency injection
  App\DataFixtures\:
    resource: '../src/DataFixtures/'
    tags: [ 'doctrine.fixture.orm' ]
